---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.16.0 # renovate: depName=aquaproj/aqua-registry

packages:
# kubernetes
- name: ahmetb/kubectl-tree@v0.4.3
- name: ahmetb/kubectx@v0.9.4
- name: ahmetb/kubectx/kubens@v0.9.4
- name: kubernetes/kubectl@v1.27.2
- name: kubernetes-sigs/kind@v0.19.0
- name: kubernetes-sigs/kustomize@kustomize/v4.5.7
- name: helm/helm@v3.12.0
- name: roboll/helmfile@v0.144.0
- name: argoproj/argo-rollouts@v1.1.1
- name: int128/ktunnels@v0.4.0
- name: vmware-tanzu/velero@v1.8.0
- name: stern/stern@v1.21.0

# git
- name: cli/cli@v2.30.0
- name: dandavison/delta@0.16.5

# terraform
- name: hashicorp/terraform@v1.5.0
- name: flosell/iam-policy-json-to-terraform@1.8.2

# terminal
- name: peco/peco@v0.5.11
- name: stedolan/jq@jq-1.6
- name: mikefarah/yq@v4.34.1
- name: direnv/direnv@v2.32.3

# opa
- name: open-policy-agent/conftest@v0.30.0
- name: open-policy-agent/opa@v0.53.1
