tap "aquaproj/aqua"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "faac", link: false
brew "faad2", link: false
brew "git"
brew "gnu-sed"
brew "go"
brew "libtool"
brew "n"
brew "tmux"
brew "tree"
brew "wget"
brew "yarn", link: false
brew "zsh"
brew "aquaproj/aqua/aqua"
cask "session-manager-plugin"
cask "google-chrome"
cask "google-japanese-ime"
cask "clipy"
cask "slack"
cask "docker"
cask "visual-studio-code"
cask "iterm2"
cask "deepl"
cask "discord"
